services:

  haproxy:
    image: haproxy:2.8
    ports:
      - "80:80"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg

  v2:
    image: stoplight/prism:5
    platform: linux/amd64
    command: mock -d -h 0.0.0.0 "/swagger/openapi_public.yaml"
    restart: always
    ports:
      - "4015:4010"
    volumes:
      - ./swagger:/swagger
