site_name: libica
nav:
  - v2: v2/README.md
  - app: app/README.md

theme:
  name:
    material
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

repo_name: umccr/libica
repo_url: https://github.com/umccr/libica

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/umccr/libica
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/umccr

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.inlinehilite
  - pymdownx.magiclink
