# coding: utf-8

"""
    Genomic Data Store Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from libica.openapi.libgds.configuration import Configuration


class VolumeFileListResponse(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'items': 'list[FileResponse]',
        'item_success_count': 'int',
        'item_failed_count': 'int',
        'items_failed': 'list[BulkFailedItem]'
    }

    attribute_map = {
        'items': 'items',
        'item_success_count': 'itemSuccessCount',
        'item_failed_count': 'itemFailedCount',
        'items_failed': 'itemsFailed'
    }

    def __init__(self, items=None, item_success_count=None, item_failed_count=None, items_failed=None, local_vars_configuration=None):  # noqa: E501
        """VolumeFileListResponse - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._items = None
        self._item_success_count = None
        self._item_failed_count = None
        self._items_failed = None
        self.discriminator = None

        if items is not None:
            self.items = items
        if item_success_count is not None:
            self.item_success_count = item_success_count
        if item_failed_count is not None:
            self.item_failed_count = item_failed_count
        if items_failed is not None:
            self.items_failed = items_failed

    @property
    def items(self):
        """Gets the items of this VolumeFileListResponse.  # noqa: E501

        Retrieved files  # noqa: E501

        :return: The items of this VolumeFileListResponse.  # noqa: E501
        :rtype: list[FileResponse]
        """
        return self._items

    @items.setter
    def items(self, items):
        """Sets the items of this VolumeFileListResponse.

        Retrieved files  # noqa: E501

        :param items: The items of this VolumeFileListResponse.  # noqa: E501
        :type: list[FileResponse]
        """

        self._items = items

    @property
    def item_success_count(self):
        """Gets the item_success_count of this VolumeFileListResponse.  # noqa: E501

        Number of items that succeeded  # noqa: E501

        :return: The item_success_count of this VolumeFileListResponse.  # noqa: E501
        :rtype: int
        """
        return self._item_success_count

    @item_success_count.setter
    def item_success_count(self, item_success_count):
        """Sets the item_success_count of this VolumeFileListResponse.

        Number of items that succeeded  # noqa: E501

        :param item_success_count: The item_success_count of this VolumeFileListResponse.  # noqa: E501
        :type: int
        """

        self._item_success_count = item_success_count

    @property
    def item_failed_count(self):
        """Gets the item_failed_count of this VolumeFileListResponse.  # noqa: E501

        Number of items that failed  # noqa: E501

        :return: The item_failed_count of this VolumeFileListResponse.  # noqa: E501
        :rtype: int
        """
        return self._item_failed_count

    @item_failed_count.setter
    def item_failed_count(self, item_failed_count):
        """Sets the item_failed_count of this VolumeFileListResponse.

        Number of items that failed  # noqa: E501

        :param item_failed_count: The item_failed_count of this VolumeFileListResponse.  # noqa: E501
        :type: int
        """

        self._item_failed_count = item_failed_count

    @property
    def items_failed(self):
        """Gets the items_failed of this VolumeFileListResponse.  # noqa: E501

        Item failures with error details  # noqa: E501

        :return: The items_failed of this VolumeFileListResponse.  # noqa: E501
        :rtype: list[BulkFailedItem]
        """
        return self._items_failed

    @items_failed.setter
    def items_failed(self, items_failed):
        """Sets the items_failed of this VolumeFileListResponse.

        Item failures with error details  # noqa: E501

        :param items_failed: The items_failed of this VolumeFileListResponse.  # noqa: E501
        :type: list[BulkFailedItem]
        """

        self._items_failed = items_failed

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VolumeFileListResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, VolumeFileListResponse):
            return True

        return self.to_dict() != other.to_dict()
