# coding: utf-8

"""
    Event Notification Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from libica.openapi.libens.configuration import Configuration


class DeliveryTarget(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'aws_sns_topic': 'DeliveryTargetAwsSnsTopic',
        'aws_sqs_queue': 'DeliveryTargetAwsSqsQueue',
        'workflow_run_launch': 'DeliveryTargetWorkflowRunLaunch'
    }

    attribute_map = {
        'aws_sns_topic': 'awsSnsTopic',
        'aws_sqs_queue': 'awsSqsQueue',
        'workflow_run_launch': 'workflowRunLaunch'
    }

    def __init__(self, aws_sns_topic=None, aws_sqs_queue=None, workflow_run_launch=None, local_vars_configuration=None):  # noqa: E501
        """DeliveryTarget - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._aws_sns_topic = None
        self._aws_sqs_queue = None
        self._workflow_run_launch = None
        self.discriminator = None

        if aws_sns_topic is not None:
            self.aws_sns_topic = aws_sns_topic
        if aws_sqs_queue is not None:
            self.aws_sqs_queue = aws_sqs_queue
        if workflow_run_launch is not None:
            self.workflow_run_launch = workflow_run_launch

    @property
    def aws_sns_topic(self):
        """Gets the aws_sns_topic of this DeliveryTarget.  # noqa: E501


        :return: The aws_sns_topic of this DeliveryTarget.  # noqa: E501
        :rtype: DeliveryTargetAwsSnsTopic
        """
        return self._aws_sns_topic

    @aws_sns_topic.setter
    def aws_sns_topic(self, aws_sns_topic):
        """Sets the aws_sns_topic of this DeliveryTarget.


        :param aws_sns_topic: The aws_sns_topic of this DeliveryTarget.  # noqa: E501
        :type: DeliveryTargetAwsSnsTopic
        """

        self._aws_sns_topic = aws_sns_topic

    @property
    def aws_sqs_queue(self):
        """Gets the aws_sqs_queue of this DeliveryTarget.  # noqa: E501


        :return: The aws_sqs_queue of this DeliveryTarget.  # noqa: E501
        :rtype: DeliveryTargetAwsSqsQueue
        """
        return self._aws_sqs_queue

    @aws_sqs_queue.setter
    def aws_sqs_queue(self, aws_sqs_queue):
        """Sets the aws_sqs_queue of this DeliveryTarget.


        :param aws_sqs_queue: The aws_sqs_queue of this DeliveryTarget.  # noqa: E501
        :type: DeliveryTargetAwsSqsQueue
        """

        self._aws_sqs_queue = aws_sqs_queue

    @property
    def workflow_run_launch(self):
        """Gets the workflow_run_launch of this DeliveryTarget.  # noqa: E501


        :return: The workflow_run_launch of this DeliveryTarget.  # noqa: E501
        :rtype: DeliveryTargetWorkflowRunLaunch
        """
        return self._workflow_run_launch

    @workflow_run_launch.setter
    def workflow_run_launch(self, workflow_run_launch):
        """Sets the workflow_run_launch of this DeliveryTarget.


        :param workflow_run_launch: The workflow_run_launch of this DeliveryTarget.  # noqa: E501
        :type: DeliveryTargetWorkflowRunLaunch
        """

        self._workflow_run_launch = workflow_run_launch

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DeliveryTarget):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, DeliveryTarget):
            return True

        return self.to_dict() != other.to_dict()
